version: "3.7"

services:
    shop:
        build: ./Shop
        container_name: shop
        networks:
            - backend
        depends_on: 
            - redis
        restart: on-failure
    customer:
        build: ./Customer
        container_name: customer
        networks: 
            - backend
        depends_on: 
            - redis
        restart: on-failure
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            - backend
            - frontend
    dashboard:
        build: ./Dashboard
        container_name: dashboard
        depends_on: 
            - redis
        restart: on-failure
        networks:
            - frontend
        ports:
            - 5000:5000
        
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge