---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    namespace: production
    name: blue-team-developer-binding
subjects:
    - kind: User
      name: dave # Name is case sensitive
      apiGroup: rbac.authorization.k8s.io
roleRef:
    kind: Role
    name: blue-team-developer
    apiGroup: rbac.authorization.k8s.io   