---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: production
    name: blue-senior-developer
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: stage
    name: blue-junior-developer
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: production
    name: red-team-senior-developer
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    namespace: stage
    name: red-team-junior-developer
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "watch", "list"]