---
apiVersion: v1 
kind: Namespace
metadata:  
    name: production 
    labels:  
        name: production
---
apiVersion: v1
kind: Namespace
metadata:
    name: stage
    labels:
        name: stage