---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deployment
    labels:
        app: onlineshop
        name: redis-deployment
spec:
    template:
        metadata:
            name: redis-pod
            labels:
                app: onlineshop
                name: redis-pod
        spec:
            containers:
                - name: redis
                  image: redis:latest
    replicas: 1
    selector:
        matchLabels:
            app: onlineshop
            name: redis-pod

---
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        app: onlineshop
        name: redis
spec:
    type: ClusterIP
    ports:
        - targetPort: 6379
          port: 6379
    selector:
        app: onlineshop
        name: redis-pod
