---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: local-pv-1
spec:
    accessModes: 
        - ReadWriteOnce
    capacity:   
        storage: 1Gi
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: /tmp/data