---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-1
    namespace: production
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi